#### **IMPORTANDO LIBRERÍA NUMPY**

In [2]:
import numpy as np

##### Creando una lista de 10 Elementos

In [3]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

##### Transformando la Lista a un Array

In [4]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Corroborando el tipo de estructura


In [5]:
type(arreglo)

numpy.ndarray

##### Corroborando el tipo de datos del arreglo


In [6]:
arreglo.dtype

dtype('int32')

##### Definiendo el Array de int32 a float32


In [7]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### Sigue siendo un array de int32


In [8]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Transformando los datos de int32 a float32


In [9]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### También existe una función similar a Range pero ocupando Arrays

In [10]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Arreglo de 2 en 2 utilizando Arange

In [11]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

<h4 style = "color:lightblue"><b>ALGUNAS FUNCIONES DE NUMPY</b></h4>
<h4 style = "color:aquamarine">Obteniendo el promedio del array</h3>


In [12]:
promedio = np.mean(arreglo)
promedio

5.5

<h4 style = "color:aquamarine">Obteniendo la mediana del array</h4>


In [13]:
mediana = np.median(arreglo)
mediana

5.5

<h4 style = "color:aquamarine"> Desviación Estandar del Arreglo </h4>


In [14]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo unos </h4>

In [15]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo ceros </h4>

In [16]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

<h4 style = "color:aquamarine"> Transformando el arreglo de unos de punto flotante a enteros </h4>


In [17]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h3 style = "color:orange"> <b>UTILIZANDO LA FUNCIÓN RANDOM</b> </h4>
<h4 style = "color:yellow"> Generando arreglo aleatorio de 5 elementos </h4>



In [18]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio 

array([0.37154104, 0.24500142, 0.97246619, 0.80770203, 0.06359299,
       0.30674744, 0.8927682 , 0.59915939, 0.34436385, 0.84542841])

<h4 style = "color:yellow"> Generando una matriz aleatoria de 3x3</h4>


In [19]:
matriz = np.random.rand(3,3)
matriz

array([[0.19008738, 0.07483656, 0.04774131],
       [0.83244999, 0.27789729, 0.98710065],
       [0.39995505, 0.36029766, 0.57263819]])

<h4 style = "color:white"> Generando un arreglo aleatorio de 10 números enteros del 1 al 5</h4>


In [23]:
arreglo_aleatorio2  = np.random.randint(1,1001,10)
arreglo_aleatorio2

array([574, 778, 364,  13, 333, 710, 264, 411,  31, 344])

<h4 style = "color:yellow"> Generando una matriz aleatoria de 10 números enteros del 1 al 100</h4>


In [21]:
matriz2 = np.random.randint(1,101,(10,10))
matriz2

array([[ 17,  71, 100,  11,  94,  65,  86,  10,  85,  73],
       [ 81,   1,  10,  47,  10,   6,  82,   5,  19,  86],
       [  9,  59,  49,  20,  65,  48,   2,  75,  23,  50],
       [ 22,  82,  44,  67,  45,  72,  85,   9,  69,  31],
       [ 56,  15,  91,  16,  58,  40,  87,  12,  14,  86],
       [ 70,  96,  77,  53,  31,  39,  61,  97,  68, 100],
       [ 95,  28,  37,   1,  60,  84,  45,  35,   9,   4],
       [ 65,  94,  32,  90,  31,  95,  21,  86,  47,  52],
       [ 85,  20,   5,  12,  76,  39,  53,  19,  89,  49],
       [ 43,  89,  44,  45,  71,  58,  40,   8,  32,  84]])

In [22]:
np.linspace(1,20,3)

array([ 1. , 10.5, 20. ])